load("@aspect_rules_js//js:defs.bzl", "js_library")
load("@npm//:defs.bzl", "npm_link_all_packages")

npm_link_all_packages(name = "node_modules")

exports_files(["config.yml"])

js_library(
    name = "jest_config",
    srcs = [
        "jest.config.cjs",
        "babel.config.cjs",
        "jest-resolver.cjs",
    ],
    visibility = ["//visibility:public"],
)
