import { getConfig } from './config.js';
import { getLogger } from './logger.js';

const _reviewTimestamps = new Map();

function isLocalEndpoint(endpoint) {
  try {
    const url = new URL(endpoint);
    const hostname = url.hostname;
    return (
      hostname === 'localhost' ||
      hostname === '127.0.0.1' ||
      hostname === '[::1]' ||
      hostname === '::1'
    );
  } catch {
    return false;
  }
}

function sanitizeAIOutput(text) {
  // Strip GitHub Actions workflow commands that could be injected
  return text.replace(/::[\w-]+(\s+[\w-]+=[\w-]+)*::.*/g, '[sanitized command]');
}

function buildReviewPrompt(prData, diff, files, maxDiffSize) {
  const truncatedDiff =
    diff.length > maxDiffSize
      ? diff.substring(0, maxDiffSize) + '\n\n[... diff truncated due to size ...]'
      : diff;

  const fileList = files.map((f) => `- ${f.filename} (+${f.additions}/-${f.deletions})`).join('\n');

  return (
    `## Pull Request #${prData.number}: ${prData.title}\n\n` +
    `**Author:** ${prData.user.login}\n` +
    `**Base:** ${prData.base.ref} ← ${prData.head.ref}\n` +
    `**Files changed:**\n${fileList}\n\n` +
    `**Description:**\n${prData.body || '(no description)'}\n\n` +
    `**Diff:**\n\`\`\`diff\n${truncatedDiff}\n\`\`\``
  );
}

async function callLocalAI(endpoint, model, systemPrompt, userPrompt, options = {}) {
  const { maxTokens = 2000, temperature = 0.3, timeout = 120000 } = options;

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeout);

  try {
    const response = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        max_tokens: maxTokens,
        temperature
      }),
      signal: controller.signal
    });

    if (!response.ok) {
      throw new Error(`AI endpoint returned ${response.status}: ${response.statusText}`);
    }

    const data = await response.json();
    return data.choices?.[0]?.message?.content || '';
  } finally {
    clearTimeout(timer);
  }
}

function formatReviewComment(aiResponse, prNumber) {
  const sanitized = sanitizeAIOutput(aiResponse);

  return (
    `## AI Code Review for PR #${prNumber}\n\n` +
    sanitized +
    '\n\n---\n' +
    '*This review was generated by a local AI model. ' +
    'It is advisory only and may contain inaccuracies.*'
  );
}

async function reviewPullRequest(octokit, owner, repo, prNumber) {
  const config = getConfig();
  const aiConfig = config.ai_review;

  if (!aiConfig?.enabled) {
    return { success: false, error: 'AI review is not enabled in configuration.' };
  }

  // Rate limiting: reject if <5min since last review on same PR
  const rateKey = `${owner}/${repo}#${prNumber}`;
  const lastReview = _reviewTimestamps.get(rateKey);
  if (lastReview && Date.now() - lastReview < 300000) {
    return {
      success: false,
      error: 'Rate limited: please wait at least 5 minutes between reviews on the same PR.'
    };
  }

  // Endpoint validation
  if (!aiConfig.allow_remote_endpoint && !isLocalEndpoint(aiConfig.endpoint)) {
    return {
      success: false,
      error: 'Remote AI endpoints are not allowed. Set allow_remote_endpoint: true to enable.'
    };
  }

  try {
    const prData = await octokit.request('GET /repos/{owner}/{repo}/pulls/{pull_number}', {
      owner,
      repo,
      pull_number: prNumber
    });

    const diffResponse = await octokit.request('GET /repos/{owner}/{repo}/pulls/{pull_number}', {
      owner,
      repo,
      pull_number: prNumber,
      mediaType: { format: 'diff' }
    });

    const filesResponse = await octokit.request(
      'GET /repos/{owner}/{repo}/pulls/{pull_number}/files',
      { owner, repo, pull_number: prNumber }
    );

    const systemPrompt =
      aiConfig.system_prompt ||
      'You are a thorough code reviewer. Analyze the PR diff and provide: 1. Summary of changes 2. Potential bugs or issues 3. Security concerns 4. Suggestions for improvement 5. Overall assessment';

    const userPrompt = buildReviewPrompt(
      prData.data,
      typeof diffResponse.data === 'string' ? diffResponse.data : '',
      filesResponse.data,
      aiConfig.max_diff_size || 12000
    );

    const aiResponse = await callLocalAI(
      aiConfig.endpoint,
      aiConfig.model || 'local-model',
      systemPrompt,
      userPrompt,
      {
        maxTokens: aiConfig.max_tokens || 2000,
        temperature: aiConfig.temperature || 0.3,
        timeout: aiConfig.timeout || 120000
      }
    );

    _reviewTimestamps.set(rateKey, Date.now());

    const comment = formatReviewComment(aiResponse, prNumber);

    await octokit.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: comment
    });

    return { success: true, comment };
  } catch (error) {
    getLogger().error(`❌ Error reviewing PR #${prNumber}:`, error.message);
    return { success: false, error: error.message };
  }
}

export {
  reviewPullRequest,
  buildReviewPrompt,
  callLocalAI,
  formatReviewComment,
  isLocalEndpoint,
  sanitizeAIOutput,
  _reviewTimestamps
};
