load("@aspect_rules_js//js:defs.bzl", "js_library")
load("@npm//:jest/package_json.bzl", jest_bin = "bin")

js_library(
    name = "test_sources",
    srcs = glob([
        "unit/**/*.test.js",
        "integration/**/*.test.js",
    ]),
    deps = [
        "//src:lib",
        "//:node_modules/jest",
        "//:node_modules/@babel/core",
        "//:node_modules/@babel/preset-env",
        "//:node_modules/babel-plugin-transform-import-meta",
    ],
)

jest_bin.jest_test(
    name = "unit_tests",
    args = [
        "--config",
        "jest.config.cjs",
        "--testPathPattern",
        "unit",
        "--no-cache",
        "--no-watchman",
    ],
    data = [
        ":test_sources",
        "//src:lib",
        "//:jest_config",
        "//:node_modules/jest",
        "//:node_modules/@babel/core",
        "//:node_modules/@babel/preset-env",
        "//:node_modules/babel-plugin-transform-import-meta",
        "//:node_modules/@types/jest",
    ],
)

jest_bin.jest_test(
    name = "integration_tests",
    args = [
        "--config",
        "jest.config.cjs",
        "--testPathPattern",
        "integration",
        "--no-cache",
        "--no-watchman",
    ],
    data = [
        ":test_sources",
        "//src:lib",
        "//:jest_config",
        "//:node_modules/jest",
        "//:node_modules/@babel/core",
        "//:node_modules/@babel/preset-env",
        "//:node_modules/babel-plugin-transform-import-meta",
        "//:node_modules/@types/jest",
    ],
)
